/**
 * CodeExportPanel — Generate code from selected shapes.
 *
 * Supports three output modes:
 *  - React JSX (with inline Tailwind-like className hints)
 *  - CSS (classes + variables)
 *  - SVG (for vector shapes and icon export)
 *
 * Open via ⌘⇧E or command palette → "Export code"
 */

import { useState, useMemo, useCallback } from 'react';
import { X, Copy, Check, Code, Layers, FileCode } from 'lucide-react';
import type { Shape, GradientStop, ShadowDef } from '../../lib/shapes';

// ── Types ─────────────────────────────────────────────────────────────────────

type CodeMode = 'react' | 'css' | 'svg';

interface Props {
  shapes: Shape[];       // all shapes on canvas
  selectedIds: string[]; // currently selected shape ids
  onClose: () => void;
}

// ── Utility helpers ───────────────────────────────────────────────────────────

/** Safe CSS identifier from a shape name */
function cssId(name: string): string {
  return (name || 'shape')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'shape';
}

/** Convert hex + opacity to rgba string */
function toRgba(hex: string, opacity = 1): string {
  const h = hex.replace('#', '');
  const r = parseInt(h.substring(0, 2), 16);
  const g = parseInt(h.substring(2, 4), 16);
  const b = parseInt(h.substring(4, 6), 16);
  if (isNaN(r) || isNaN(g) || isNaN(b)) return hex;
  return opacity < 1 ? `rgba(${r}, ${g}, ${b}, ${opacity})` : `rgb(${r}, ${g}, ${b})`;
}

/** Build a CSS gradient string */
function buildGradient(shape: Shape): string {
  const stops = (shape.gradientStops || [])
    .map((s: GradientStop) => `${s.color} ${Math.round(s.position * 100)}%`)
    .join(', ');
  if (shape.fillType === 'radial-gradient') {
    return `radial-gradient(circle, ${stops})`;
  }
  return `linear-gradient(${shape.gradientAngle ?? 135}deg, ${stops})`;
}

/** Build CSS box-shadow string from a shape's shadow properties */
function buildShadow(shape: Shape): string {
  if (shape.shadows && shape.shadows.length > 0) {
    return shape.shadows
      .map((s: ShadowDef) => {
        const inset = s.inset ? 'inset ' : '';
        const spread = s.spread ? ` ${s.spread}px` : '';
        return `${inset}${s.x}px ${s.y}px ${s.blur}px${spread} ${s.color}`;
      })
      .join(', ');
  }
  if (shape.shadow) {
    return `${shape.shadowX}px ${shape.shadowY}px ${shape.shadowBlur}px ${shape.shadowColor}`;
  }
  return '';
}

/** Build CSS filter string */
function buildFilter(shape: Shape): string {
  const parts: string[] = [];
  if (shape.filterBlur) parts.push(`blur(${shape.filterBlur}px)`);
  if (shape.filterBrightness && shape.filterBrightness !== 100) parts.push(`brightness(${shape.filterBrightness}%)`);
  if (shape.filterContrast && shape.filterContrast !== 100) parts.push(`contrast(${shape.filterContrast}%)`);
  if (shape.filterSaturate && shape.filterSaturate !== 100) parts.push(`saturate(${shape.filterSaturate}%)`);
  return parts.join(' ');
}

/** Build CSS border-radius string */
function buildBorderRadius(br: Shape['borderRadius']): string {
  if (typeof br === 'number') {
    return br === 0 ? '' : `${br}px`;
  }
  if (Array.isArray(br)) {
    const [tl, tr, br2, bl] = br;
    if (tl === tr && tr === br2 && br2 === bl) return `${tl}px`;
    return `${tl}px ${tr}px ${br2}px ${bl}px`;
  }
  return '';
}

/** Collect shape + all descendants in depth-first order */
function collectTree(shapes: Shape[], rootId: string): Shape[] {
  const byId = new Map(shapes.map(s => [s.id, s]));
  const result: Shape[] = [];
  const visit = (id: string) => {
    const s = byId.get(id);
    if (!s) return;
    result.push(s);
    shapes.filter(c => c.parentId === id).forEach(c => visit(c.id));
  };
  visit(rootId);
  return result;
}

// ── CSS Generator ─────────────────────────────────────────────────────────────

function generateCSS(shapes: Shape[], selectedIds: string[], allShapes: Shape[]): string {
  const targets = selectedIds.length > 0
    ? selectedIds.flatMap(id => collectTree(allShapes, id))
    : shapes.slice(0, 20);

  const seen = new Set<string>();
  const unique = targets.filter(s => {
    if (seen.has(s.id)) return false;
    seen.add(s.id);
    return true;
  });

  const lines: string[] = [
    '/* Generated by Quill Design Tool */',
    '/* Selection: ' + unique.map(s => s.name || s.type).join(', ') + ' */',
    '',
  ];

  for (const shape of unique) {
    if (shape.hidden) continue;
    const cls = cssId(shape.name || shape.type + '-' + shape.id.slice(0, 6));
    const props: string[] = [];

    // Position + size
    props.push(`  position: absolute;`);
    props.push(`  left: ${Math.round(shape.x)}px;`);
    props.push(`  top: ${Math.round(shape.y)}px;`);
    props.push(`  width: ${Math.round(shape.width)}px;`);
    props.push(`  height: ${Math.round(shape.height)}px;`);

    // Background / fill
    if (shape.fillType === 'linear-gradient' || shape.fillType === 'radial-gradient') {
      props.push(`  background: ${buildGradient(shape)};`);
    } else if (shape.fillType === 'image' && shape.imageUrl) {
      props.push(`  background-image: url('${shape.imageUrl}');`);
      props.push(`  background-size: ${shape.imageFit === 'tile' ? 'auto' : shape.imageFit === 'fit' ? 'contain' : 'cover'};`);
      props.push(`  background-position: center;`);
      props.push(`  background-repeat: ${shape.imageFit === 'tile' ? 'repeat' : 'no-repeat'};`);
    } else if (shape.fill && shape.fill !== 'transparent') {
      const bg = shape.fillOpacity < 1 ? toRgba(shape.fill, shape.fillOpacity) : shape.fill;
      props.push(`  background-color: ${bg};`);
    }

    // Border
    if (shape.stroke && shape.stroke !== 'transparent' && shape.strokeWidth > 0) {
      props.push(`  border: ${shape.strokeWidth}px solid ${shape.stroke};`);
      if (shape.strokePosition === 'inside') props.push(`  box-sizing: border-box;`);
    }

    // Border radius
    const br = buildBorderRadius(shape.borderRadius);
    if (br) props.push(`  border-radius: ${br};`);
    if (shape.type === 'ellipse') props.push(`  border-radius: 50%;`);

    // Typography
    if (shape.type === 'text') {
      if (shape.color) props.push(`  color: ${shape.color};`);
      if (shape.fontSize) props.push(`  font-size: ${shape.fontSize}px;`);
      if (shape.fontFamily) props.push(`  font-family: '${shape.fontFamily}', sans-serif;`);
      if (shape.fontWeight && shape.fontWeight !== '400') props.push(`  font-weight: ${shape.fontWeight};`);
      if (shape.fontStyle && shape.fontStyle !== 'normal') props.push(`  font-style: ${shape.fontStyle};`);
      if (shape.textAlign && shape.textAlign !== 'left') props.push(`  text-align: ${shape.textAlign};`);
      if (shape.lineHeight && shape.lineHeight !== 1) props.push(`  line-height: ${shape.lineHeight};`);
      if (shape.letterSpacing) props.push(`  letter-spacing: ${(shape.letterSpacing / 100).toFixed(3)}em;`);
      if (shape.textDecoration && shape.textDecoration !== 'none') props.push(`  text-decoration: ${shape.textDecoration};`);
    }

    // Opacity
    if (shape.opacity < 1) props.push(`  opacity: ${shape.opacity};`);

    // Shadow
    const shadow = buildShadow(shape);
    if (shadow) props.push(`  box-shadow: ${shadow};`);

    // Backdrop blur (glassmorphism)
    if (shape.filterBackdropBlur) {
      props.push(`  backdrop-filter: blur(${shape.filterBackdropBlur}px);`);
      props.push(`  -webkit-backdrop-filter: blur(${shape.filterBackdropBlur}px);`);
    }

    // Filter
    const filter = buildFilter(shape);
    if (filter) props.push(`  filter: ${filter};`);

    // Blend mode
    if (shape.blendMode && shape.blendMode !== 'normal') {
      props.push(`  mix-blend-mode: ${shape.blendMode};`);
    }

    // Rotation / flip
    const transforms: string[] = [];
    if (shape.rotation) transforms.push(`rotate(${shape.rotation}deg)`);
    if (shape.flipX) transforms.push(`scaleX(-1)`);
    if (shape.flipY) transforms.push(`scaleY(-1)`);
    if (transforms.length) props.push(`  transform: ${transforms.join(' ')};`);

    // Auto-layout (flex)
    if (shape.layout && shape.layout !== 'none') {
      props.push(`  display: flex;`);
      props.push(`  flex-direction: ${shape.layout === 'row' ? 'row' : 'column'};`);
      if (shape.layoutGap) props.push(`  gap: ${shape.layoutGap}px;`);
      if (shape.layoutPaddingH || shape.layoutPaddingV) {
        props.push(`  padding: ${shape.layoutPaddingV || 0}px ${shape.layoutPaddingH || 0}px;`);
      }
      if (shape.layoutAlign) props.push(`  align-items: ${shape.layoutAlign};`);
      if (shape.layoutJustify) props.push(`  justify-content: ${shape.layoutJustify};`);
    }

    // Overflow clip
    if (shape.clipContents) props.push(`  overflow: hidden;`);

    // Scroll
    if (shape.scrollDirection && shape.scrollDirection !== 'none') {
      if (shape.scrollDirection === 'vertical') props.push(`  overflow-y: auto;`);
      else if (shape.scrollDirection === 'horizontal') props.push(`  overflow-x: auto;`);
      else props.push(`  overflow: auto;`);
    }

    // Transition
    if (shape.transitionDuration) {
      const props2 = shape.transitionProperties?.join(', ') || 'all';
      const ease = shape.transitionEasing || 'ease';
      props.push(`  transition: ${props2} ${shape.transitionDuration}ms ${ease};`);
    }

    // Notes as comment
    if (shape.notes) {
      lines.push(`/* ${shape.name || shape.type}: ${shape.notes} */`);
    }

    lines.push(`.${cls} {`);
    lines.push(...props);
    lines.push(`}`);
    lines.push('');
  }

  return lines.join('\n');
}

// ── React JSX Generator ───────────────────────────────────────────────────────

function shapeToInlineStyle(shape: Shape): Record<string, string | number> {
  const style: Record<string, string | number> = {
    position: 'absolute',
    left: Math.round(shape.x),
    top: Math.round(shape.y),
    width: Math.round(shape.width),
    height: Math.round(shape.height),
  };

  // Background
  if (shape.fillType === 'linear-gradient' || shape.fillType === 'radial-gradient') {
    style.background = buildGradient(shape);
  } else if (shape.fill && shape.fill !== 'transparent') {
    style.backgroundColor = shape.fillOpacity < 1 ? toRgba(shape.fill, shape.fillOpacity) : shape.fill;
  }

  // Border
  if (shape.stroke && shape.stroke !== 'transparent' && shape.strokeWidth > 0) {
    style.border = `${shape.strokeWidth}px solid ${shape.stroke}`;
  }

  // Radius
  const br = shape.type === 'ellipse' ? '50%' : buildBorderRadius(shape.borderRadius);
  if (br) style.borderRadius = br;

  // Typography
  if (shape.type === 'text') {
    if (shape.color) style.color = shape.color;
    if (shape.fontSize) style.fontSize = shape.fontSize;
    if (shape.fontFamily) style.fontFamily = `'${shape.fontFamily}', sans-serif`;
    if (shape.fontWeight) style.fontWeight = shape.fontWeight;
    if (shape.fontStyle && shape.fontStyle !== 'normal') style.fontStyle = shape.fontStyle;
    if (shape.textAlign) style.textAlign = shape.textAlign;
    if (shape.lineHeight) style.lineHeight = shape.lineHeight;
  }

  // Opacity
  if (shape.opacity < 1) style.opacity = shape.opacity;

  // Shadow
  const shadow = buildShadow(shape);
  if (shadow) style.boxShadow = shadow;

  // Backdrop blur
  if (shape.filterBackdropBlur) {
    style.backdropFilter = `blur(${shape.filterBackdropBlur}px)`;
  }

  // Blend
  if (shape.blendMode && shape.blendMode !== 'normal') style.mixBlendMode = shape.blendMode;

  // Transforms
  const transforms: string[] = [];
  if (shape.rotation) transforms.push(`rotate(${shape.rotation}deg)`);
  if (shape.flipX) transforms.push(`scaleX(-1)`);
  if (shape.flipY) transforms.push(`scaleY(-1)`);
  if (transforms.length) style.transform = transforms.join(' ');

  // Layout
  if (shape.layout && shape.layout !== 'none') {
    style.display = 'flex';
    style.flexDirection = shape.layout;
    if (shape.layoutGap) style.gap = shape.layoutGap;
    if (shape.layoutPaddingH) style.paddingLeft = style.paddingRight = shape.layoutPaddingH;
    if (shape.layoutPaddingV) style.paddingTop = style.paddingBottom = shape.layoutPaddingV;
    if (shape.layoutAlign) style.alignItems = shape.layoutAlign;
    if (shape.layoutJustify) style.justifyContent = shape.layoutJustify;
  }

  if (shape.clipContents) style.overflow = 'hidden';

  return style;
}

function styleToJSX(style: Record<string, string | number>): string {
  const entries = Object.entries(style).map(([k, v]) => {
    const val = typeof v === 'string' ? `"${v}"` : `{${v}}`;
    return `    ${k}: ${val}`;
  });
  return `{{\n${entries.join(',\n')}\n  }}`;
}

function generateReact(shapes: Shape[], selectedIds: string[], allShapes: Shape[]): string {
  const targets = selectedIds.length > 0
    ? selectedIds.flatMap(id => collectTree(allShapes, id))
    : shapes.slice(0, 10);

  const seen = new Set<string>();
  const unique = targets.filter(s => {
    if (seen.has(s.id)) return false;
    seen.add(s.id);
    return true;
  });

  const lines: string[] = [
    '// Generated by Quill Design Tool',
    '// Selection: ' + unique.map(s => s.name || s.type).join(', '),
    '',
    'export default function Component() {',
    '  return (',
    '    <div style={{ position: "relative", width: "100%", height: "100%" }}>',
  ];

  for (const shape of unique) {
    if (shape.hidden) continue;
    const name = shape.name || shape.type;
    const style = shapeToInlineStyle(shape);
    const styleStr = styleToJSX(style);

    if (shape.type === 'text') {
      const tag = (shape.fontSize || 0) > 28 ? 'h2' : (shape.fontSize || 0) > 20 ? 'h3' : 'p';
      lines.push(`      {/* ${name} */}`);
      lines.push(`      <${tag} style=${styleStr}>`);
      lines.push(`        ${(shape.text || '').replace(/</g, '&lt;')}`);
      lines.push(`      </${tag}>`);
    } else if (shape.type === 'frame' || shape.type === 'rectangle') {
      const hasChildren = unique.some(s => s.parentId === shape.id);
      if (hasChildren) {
        lines.push(`      {/* ${name} */}`);
        lines.push(`      <div style=${styleStr}>`);
        // Children will be rendered in the next iteration but need indenting
        lines.push(`        {/* children */}`);
        lines.push(`      </div>`);
      } else {
        lines.push(`      {/* ${name} */}`);
        lines.push(`      <div style=${styleStr} />`);
      }
    } else if (shape.type === 'ellipse') {
      lines.push(`      {/* ${name} */}`);
      lines.push(`      <div style=${styleStr} />`);
    } else if (shape.type === 'path') {
      lines.push(`      {/* ${name} — path shape: consider using an SVG <path> element */}`);
      lines.push(`      <div style=${styleStr} />`);
    }
    lines.push('');
  }

  lines.push('    </div>');
  lines.push('  );');
  lines.push('}');

  return lines.join('\n');
}

// ── SVG Generator ─────────────────────────────────────────────────────────────

function generateSVG(shapes: Shape[], selectedIds: string[], allShapes: Shape[]): string {
  const targets = selectedIds.length > 0
    ? selectedIds.flatMap(id => collectTree(allShapes, id))
    : shapes.slice(0, 20);

  const seen = new Set<string>();
  const unique = targets.filter(s => {
    if (seen.has(s.id)) return false;
    seen.add(s.id);
    return true;
  });

  if (unique.length === 0) return '<!-- no shapes selected -->';

  // Compute bounding box
  const minX = Math.min(...unique.map(s => s.x));
  const minY = Math.min(...unique.map(s => s.y));
  const maxX = Math.max(...unique.map(s => s.x + s.width));
  const maxY = Math.max(...unique.map(s => s.y + s.height));
  const W = maxX - minX;
  const H = maxY - minY;

  const svgLines: string[] = [
    `<svg width="${Math.round(W)}" height="${Math.round(H)}" viewBox="${Math.round(minX)} ${Math.round(minY)} ${Math.round(W)} ${Math.round(H)}" xmlns="http://www.w3.org/2000/svg">`,
    `  <!-- Generated by Quill Design Tool -->`,
  ];

  // Defs for gradients
  const defs: string[] = [];

  for (const shape of unique) {
    if (shape.hidden) continue;

    let fillAttr = 'none';
    if (shape.fillType === 'linear-gradient' || shape.fillType === 'radial-gradient') {
      const gradId = `grad-${shape.id.slice(0, 8)}`;
      if (shape.fillType === 'linear-gradient') {
        const rad = ((shape.gradientAngle ?? 135) * Math.PI) / 180;
        const x1 = Math.round((0.5 - Math.cos(rad) * 0.5) * 100);
        const y1 = Math.round((0.5 - Math.sin(rad) * 0.5) * 100);
        const x2 = Math.round((0.5 + Math.cos(rad) * 0.5) * 100);
        const y2 = Math.round((0.5 + Math.sin(rad) * 0.5) * 100);
        defs.push(`    <linearGradient id="${gradId}" x1="${x1}%" y1="${y1}%" x2="${x2}%" y2="${y2}%">`);
      } else {
        defs.push(`    <radialGradient id="${gradId}" cx="50%" cy="50%" r="50%">`);
      }
      for (const stop of shape.gradientStops || []) {
        const opacity = stop.opacity ?? 1;
        defs.push(`      <stop offset="${Math.round(stop.position * 100)}%" stop-color="${stop.color}" stop-opacity="${opacity}" />`);
      }
      defs.push(`    </${shape.fillType === 'linear-gradient' ? 'linearGradient' : 'radialGradient'}>`);
      fillAttr = `url(#${gradId})`;
    } else if (shape.fill && shape.fill !== 'transparent') {
      fillAttr = shape.fill;
    }

    const strokeAttr = (shape.stroke && shape.stroke !== 'transparent' && shape.strokeWidth > 0)
      ? `stroke="${shape.stroke}" stroke-width="${shape.strokeWidth}"` : '';

    const opacityAttr = shape.opacity < 1 ? `opacity="${shape.opacity}"` : '';
    const nameComment = `  <!-- ${shape.name || shape.type} -->`;

    if (shape.type === 'ellipse') {
      const cx = shape.x + shape.width / 2;
      const cy = shape.y + shape.height / 2;
      const rx = shape.width / 2;
      const ry = shape.height / 2;
      svgLines.push(nameComment);
      svgLines.push(`  <ellipse cx="${cx.toFixed(1)}" cy="${cy.toFixed(1)}" rx="${rx.toFixed(1)}" ry="${ry.toFixed(1)}" fill="${fillAttr}" ${strokeAttr} ${opacityAttr} />`);
    } else if (shape.type === 'text') {
      svgLines.push(nameComment);
      const y = shape.y + (shape.fontSize || 16);
      svgLines.push(`  <text x="${shape.x}" y="${y}" font-family="${shape.fontFamily || 'sans-serif'}" font-size="${shape.fontSize || 16}" fill="${shape.color || '#000000'}" ${opacityAttr}>${(shape.text || '').replace(/&/g, '&amp;').replace(/</g, '&lt;')}</text>`);
    } else if (shape.type === 'path' && shape.points && shape.points.length > 0) {
      // Build SVG path from bezier points
      const pts = shape.points;
      let d = `M ${pts[0].x} ${pts[0].y}`;
      for (let i = 1; i < pts.length; i++) {
        const prev = pts[i - 1];
        const curr = pts[i];
        if (prev.cp2x !== undefined && curr.cp1x !== undefined) {
          d += ` C ${prev.cp2x} ${prev.cp2y} ${curr.cp1x} ${curr.cp1y} ${curr.x} ${curr.y}`;
        } else if (prev.cp2x !== undefined) {
          d += ` Q ${prev.cp2x} ${prev.cp2y} ${curr.x} ${curr.y}`;
        } else {
          d += ` L ${curr.x} ${curr.y}`;
        }
      }
      if (shape.pathClosed) d += ' Z';
      svgLines.push(nameComment);
      svgLines.push(`  <path d="${d}" fill="${fillAttr}" ${strokeAttr} ${opacityAttr} />`);
    } else {
      // Rectangle / frame — check border radius
      const br = shape.borderRadius;
      let rxAttr = '';
      if (typeof br === 'number' && br > 0) rxAttr = `rx="${br}"`;
      else if (Array.isArray(br) && br.some(v => v > 0)) {
        // Approximate: use average of corners
        const avg = Math.round(br.reduce((a, b) => a + b, 0) / 4);
        rxAttr = `rx="${avg}"`;
      }
      svgLines.push(nameComment);
      svgLines.push(`  <rect x="${shape.x}" y="${shape.y}" width="${shape.width}" height="${shape.height}" ${rxAttr} fill="${fillAttr}" ${strokeAttr} ${opacityAttr} />`);
    }
  }

  if (defs.length > 0) {
    // Insert defs after opening tag
    svgLines.splice(1, 0, '  <defs>', ...defs, '  </defs>');
  }

  svgLines.push('</svg>');
  return svgLines.join('\n');
}

// ── Panel Component ───────────────────────────────────────────────────────────

const MODE_TABS: { id: CodeMode; label: string; icon: React.ReactNode }[] = [
  { id: 'react', label: 'React JSX', icon: <Code size={13} /> },
  { id: 'css', label: 'CSS', icon: <FileCode size={13} /> },
  { id: 'svg', label: 'SVG', icon: <Layers size={13} /> },
];

export function CodeExportPanel({ shapes, selectedIds, onClose }: Props) {
  const [mode, setMode] = useState<CodeMode>('react');
  const [copied, setCopied] = useState(false);

  const code = useMemo(() => {
    if (mode === 'react') return generateReact(shapes, selectedIds, shapes);
    if (mode === 'css') return generateCSS(shapes, selectedIds, shapes);
    return generateSVG(shapes, selectedIds, shapes);
  }, [shapes, selectedIds, mode]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [code]);

  const selectedCount = selectedIds.length;
  const label = selectedCount === 0
    ? 'all shapes'
    : selectedCount === 1
      ? (shapes.find(s => s.id === selectedIds[0])?.name || '1 shape')
      : `${selectedCount} shapes`;

  return (
    <div
      style={{
        position: 'fixed',
        top: 48,
        right: 280,
        width: 520,
        maxHeight: 'calc(100vh - 96px)',
        background: 'var(--panel)',
        border: '1px solid var(--border)',
        borderRadius: 12,
        boxShadow: '0 16px 48px rgba(0,0,0,0.4)',
        zIndex: 8500,
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '10px 14px',
        borderBottom: '1px solid var(--border)',
        flexShrink: 0,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Code size={14} color="var(--accent)" />
          <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text)' }}>Code Export</span>
          <span style={{
            fontSize: 10, background: 'rgba(99,102,241,0.12)', color: 'var(--accent)',
            borderRadius: 4, padding: '1px 6px', fontWeight: 600,
          }}>
            {label}
          </span>
        </div>
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          <button
            onClick={handleCopy}
            style={{
              display: 'flex', alignItems: 'center', gap: 5,
              background: copied ? 'rgba(34,197,94,0.15)' : 'rgba(99,102,241,0.12)',
              border: `1px solid ${copied ? 'rgba(34,197,94,0.3)' : 'rgba(99,102,241,0.25)'}`,
              color: copied ? '#22c55e' : 'var(--accent)',
              borderRadius: 6, padding: '4px 10px',
              fontSize: 11, fontWeight: 600, cursor: 'pointer',
              transition: 'all 0.2s',
            }}
          >
            {copied ? <Check size={12} /> : <Copy size={12} />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <button
            onClick={onClose}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              color: 'var(--muted)', display: 'flex', alignItems: 'center',
              borderRadius: 4, padding: 3,
            }}
            onMouseEnter={e => { e.currentTarget.style.color = 'var(--text)'; }}
            onMouseLeave={e => { e.currentTarget.style.color = 'var(--muted)'; }}
          >
            <X size={14} />
          </button>
        </div>
      </div>

      {/* Mode tabs */}
      <div style={{
        display: 'flex', borderBottom: '1px solid var(--border)',
        padding: '0 14px', flexShrink: 0,
      }}>
        {MODE_TABS.map(tab => (
          <button
            key={tab.id}
            onClick={() => setMode(tab.id)}
            style={{
              display: 'flex', alignItems: 'center', gap: 5,
              padding: '7px 12px',
              background: 'none', border: 'none', cursor: 'pointer',
              fontSize: 11, fontWeight: mode === tab.id ? 600 : 400,
              color: mode === tab.id ? 'var(--accent)' : 'var(--muted)',
              borderBottom: `2px solid ${mode === tab.id ? 'var(--accent)' : 'transparent'}`,
              marginBottom: -1,
              transition: 'color 0.1s',
            }}
          >
            {tab.icon}
            {tab.label}
          </button>
        ))}
        <div style={{ flex: 1 }} />
        {mode === 'react' && (
          <div style={{ fontSize: 10, color: 'var(--muted)', alignSelf: 'center', paddingRight: 4 }}>
            inline styles · absolute positioning
          </div>
        )}
        {mode === 'css' && (
          <div style={{ fontSize: 10, color: 'var(--muted)', alignSelf: 'center', paddingRight: 4 }}>
            class-based · absolute positioning
          </div>
        )}
        {mode === 'svg' && (
          <div style={{ fontSize: 10, color: 'var(--muted)', alignSelf: 'center', paddingRight: 4 }}>
            scalable vector · gradients included
          </div>
        )}
      </div>

      {/* Code area */}
      <div style={{ flex: 1, overflow: 'auto', position: 'relative' }}>
        <pre
          style={{
            margin: 0,
            padding: '14px 16px',
            fontSize: 11,
            lineHeight: 1.6,
            color: 'var(--text)',
            fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', 'Consolas', monospace",
            whiteSpace: 'pre',
            overflowX: 'auto',
            minHeight: 300,
            background: 'transparent',
          }}
        >
          <SyntaxHighlight code={code} mode={mode} />
        </pre>
      </div>

      {/* Footer */}
      <div style={{
        padding: '6px 14px',
        borderTop: '1px solid var(--border)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        flexShrink: 0,
      }}>
        <span style={{ fontSize: 10, color: 'var(--muted)' }}>
          {code.split('\n').length} lines · {code.length.toLocaleString()} chars
        </span>
        <span style={{ fontSize: 10, color: 'var(--subtle)' }}>
          ⌘⇧E to toggle
        </span>
      </div>
    </div>
  );
}

// ── Syntax Highlighter ────────────────────────────────────────────────────────
// Lightweight regex-based tokenizer — no external deps

interface TokenSpan {
  text: string;
  color: string;
}

function tokenizeReact(code: string): TokenSpan[] {
  const spans: TokenSpan[] = [];
  let remaining = code;

  while (remaining.length > 0) {
    // Comment
    let m = remaining.match(/^(\/\/[^\n]*|\/\*[\s\S]*?\*\/)/);
    if (m) { spans.push({ text: m[1], color: '#6b7280' }); remaining = remaining.slice(m[1].length); continue; }

    // JSX tag
    m = remaining.match(new RegExp('^(<\\/?[A-Za-z][A-Za-z0-9.]*|>|\\/>)'));
    if (m) { spans.push({ text: m[1], color: '#7dd3fc' }); remaining = remaining.slice(m[1].length); continue; }

    // JSX attribute
    m = remaining.match(/^([a-z][a-zA-Z]*)(?==)/);
    if (m) { spans.push({ text: m[1], color: '#86efac' }); remaining = remaining.slice(m[1].length); continue; }

    // String
    m = remaining.match(/^("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`)/);
    if (m) { spans.push({ text: m[1], color: '#fbbf24' }); remaining = remaining.slice(m[1].length); continue; }

    // Keyword
    m = remaining.match(/^(export|default|function|return|const|let|var|import|from|if|else)\b/);
    if (m) { spans.push({ text: m[1], color: '#c084fc' }); remaining = remaining.slice(m[1].length); continue; }

    // Number
    m = remaining.match(/^\b(\d+(?:\.\d+)?)\b/);
    if (m) { spans.push({ text: m[1], color: '#fb923c' }); remaining = remaining.slice(m[1].length); continue; }

    // Default: one char
    spans.push({ text: remaining[0], color: 'var(--text)' });
    remaining = remaining.slice(1);
  }
  return spans;
}

function tokenizeCSS(code: string): TokenSpan[] {
  const spans: TokenSpan[] = [];
  let remaining = code;

  while (remaining.length > 0) {
    // Comment
    let m = remaining.match(/^(\/\*[\s\S]*?\*\/|\/\/[^\n]*)/);
    if (m) { spans.push({ text: m[1], color: '#6b7280' }); remaining = remaining.slice(m[1].length); continue; }

    // Selector
    m = remaining.match(/^(\.[a-zA-Z][a-zA-Z0-9_-]*(?:\s*,\s*\.[a-zA-Z][a-zA-Z0-9_-]*)*)(?=\s*\{)/);
    if (m) { spans.push({ text: m[1], color: '#7dd3fc' }); remaining = remaining.slice(m[1].length); continue; }

    // Property name
    m = remaining.match(/^(\s+)([a-z-]+)(?=\s*:)/);
    if (m) {
      spans.push({ text: m[1], color: 'var(--text)' });
      spans.push({ text: m[2], color: '#86efac' });
      remaining = remaining.slice(m[0].length);
      continue;
    }

    // Hex color
    m = remaining.match(/^(#[0-9a-fA-F]{3,8})\b/);
    if (m) { spans.push({ text: m[1], color: '#fbbf24' }); remaining = remaining.slice(m[1].length); continue; }

    // Number + unit
    m = remaining.match(/^(-?\d+(?:\.\d+)?(?:px|em|rem|%|deg|s|ms)?)\b/);
    if (m) { spans.push({ text: m[1], color: '#fb923c' }); remaining = remaining.slice(m[1].length); continue; }

    // Keywords
    m = remaining.match(/^(linear-gradient|radial-gradient|rgba|rgb|url|absolute|relative|flex|auto|none|normal|bold|italic|solid|center|cover|contain)\b/);
    if (m) { spans.push({ text: m[1], color: '#c084fc' }); remaining = remaining.slice(m[1].length); continue; }

    spans.push({ text: remaining[0], color: 'var(--text)' });
    remaining = remaining.slice(1);
  }
  return spans;
}

function tokenizeSVG(code: string): TokenSpan[] {
  const spans: TokenSpan[] = [];
  let remaining = code;

  while (remaining.length > 0) {
    // Comment
    let m = remaining.match(/^(<!--[\s\S]*?-->)/);
    if (m) { spans.push({ text: m[1], color: '#6b7280' }); remaining = remaining.slice(m[1].length); continue; }

    // Tag name
    m = remaining.match(/^(<\/?)([a-zA-Z][a-zA-Z0-9]*)/);
    if (m) {
      spans.push({ text: m[1], color: 'var(--text)' });
      spans.push({ text: m[2], color: '#7dd3fc' });
      remaining = remaining.slice(m[0].length);
      continue;
    }

    // Attribute name
    m = remaining.match(/^([a-zA-Z][a-zA-Z0-9:-]*)(?==)/);
    if (m) { spans.push({ text: m[1], color: '#86efac' }); remaining = remaining.slice(m[1].length); continue; }

    // Attribute value
    m = remaining.match(/^("(?:[^"\\]|\\.)*")/);
    if (m) { spans.push({ text: m[1], color: '#fbbf24' }); remaining = remaining.slice(m[1].length); continue; }

    spans.push({ text: remaining[0], color: 'var(--text)' });
    remaining = remaining.slice(1);
  }
  return spans;
}

function SyntaxHighlight({ code, mode }: { code: string; mode: CodeMode }) {
  const spans = useMemo(() => {
    if (mode === 'react') return tokenizeReact(code);
    if (mode === 'css') return tokenizeCSS(code);
    return tokenizeSVG(code);
  }, [code, mode]);

  return (
    <>
      {spans.map((span, i) => (
        <span key={i} style={{ color: span.color }}>{span.text}</span>
      ))}
    </>
  );
}
